controller_frequency: 10.0
recovery_behavior_enabled: true
clearing_rotation_allowed: false
recovery_behaviors: [{name: aggressive_clearance,
type: clear_costmap_recovery/ClearCostmapRecovery}]
aggressive_clearance:
   reset_distance: 0.0
max_replanning_tries: 3
planner_patience: 5.0
planner_frequency: 0.2
controller_patience: 15.0
TrajectoryPlannerROS:
  max_vel_x: 0.85
  min_vel_x: 0.1
  max_vel_theta: 0.7
  min_vel_theta: -0.7
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 3.5
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  escape_vel: −0.1
  escape_reset_dist: 0.15
  escape_reset_theta: 0.15
  holonomic_robot: false
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.3
  latch_xy_goal_tolerance: false
  pdist_scale: 0.6
  gdist_scale: 0.8
  meter_scoring: true
  occdist_scale: 0.05
  oscillation_reset_dist: 0.25
  oscillation_reset_timeout: 10.0
  prune_plan: false
  sim_time: 1.5
  sim_granularity: 0.025
  vx_samples: 10
  vtheta_samples: 20
  dwa: true
