global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 2.0
   publish_frequency: 0.1
   width: 20.0
   height: 20.0
   transform_tolerance: 0.25
   resolution: 0.02
   static_map: true
   rolling_window: false
   track_unknown_space: true
   unknown_cost_value: 255