local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 10.0
   publish_frequency: 0.2
   width: 6.0
   height: 6.0
   resolution: 0.02
   transform_tolerance: 0.15
   static_map: false
   rolling_window: true